language: ruby
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake cucumber
script:
  - bundle exec rake ci:tests
notifications:
  email: false
services:
  - postgresql