language: ruby
cache: bundler
before_script:
- export RAILS_ENV=test
- bundle exec rake db:drop
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:create --all
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rake cucumber
before_install:
- openssl aes-256-cbc -K $encrypted_11cd8d428410_key -iv $encrypted_11cd8d428410_iv
-in id_rsa.enc -out ~\/.ssh/id_rsa -d
notifications:
  email: false
services:
- postgresql
addons:
  chrome: stable
env:
  matrix:
  - CI=true
  global:
  - secure: 8cOyODZYIYZkF4Tt2miNbaJQ32DVEDqvnYKM0ZnuGMoECYkawZgxGs0k3aesWHsydubXrufsw+yLwpy02KEJmjL8RNms4uR9vzuc2JBfSUFQnTlAZpbKLP1Y0Hs6KJlsMmY+0CR0EP7DsmNCg/dHNxwB2zlimxo1ho/336w+COap6dH6yd9DP3r9rYL4Z9f1cEU/Ru1o7USJFs75uZEYfEIeD8fBypagf59TFsVLDSIRbeCa6Y8KgIjzOGvrE42MwwsneOihZ1jjE1AhxLAWWwLoQjvxM7Ael6FHbos9FiSxFd1yZM/AuepgmiaDHf3mcdYlbh9tgri/2uk1CaIvVHe9KlGiph0KrUluk91JqgIgnefEF+OMCzuq9xTsJ0d5TGlZVNogwAYCG+2nM2lHBazVwYg6Ugzm4rIB91X1WgwVKGBWShw/Xc8bzpDvVccaGNXRalN+kYlxIZRpCSW9aBK7gcP/3d4nGYrWS8TQcmMKBHpw4zA4eha3ePESP1fcg0JX9hruhxNGw9X7e65ufNirt+q4s6Nk1uq08+M/H6DdU564qOECamu9W/tZwWL9GlupWZjZqzqPRoVjyhs7Ef6H7E79D3zllxwPl/8DgWLGvsC3GUZxxHg2NTGefQGDfZpIP6MvvMjyduh5r0L8JAc9F4QuJqRDNkt760hXhuw=
  - secure: G9k2cNhXxZLQwq8zOgt8NFWnJsb8j+ajp4p30LPbYPY+XRZ7x3bv1cYaE7AWNKSexaTAspcWSz8Rui2ptJfdE1GQRLcS/CZi0binMzv2colxxqUDEJxG/eg55BJ7qshC+nJePokOj3dxrYvKj+RUhxkT/zILXWCEUMMxwuWG0n2Z6cju+rZCCO2waNXQxpLb3awHM+cMM216R1wXUHtFsp49D9XHkGhcO6oNVi9+mSgPqOYzDkItAk78YFjFZLgR8hMT8NKwnUonX7dgIMfbDp4OW8qHoLJQLRDuau7USrA697g/p5jN/FWKJO2fBD9PhuYGI5ISfFVCP+HySQmcKj9jrqcRZwrmxoQPv7OfkEby9oi+1TTKBLDprhSVELB1QKB7hNfpNIFiqCKlq+xGMoqAJMkVYZGUrnx6dPmPQqNhYmHKBjaWawam2H5yFdyHMK5y+8Ru8r3+On3n+bX5Nq6v+/1bFi1UkusowzFJbpsVIRJpULcFrg+KsxRWtv+40ZHlfPZ4PYFTcNnrSzk2JtFulTpSlQmnkSkWshU7YgomHfx5GVP0hCKEc+ac0th+Y53guNn6EhEb5HrPXRnvH6l6XtZvjCn6VsM4Xvev+4S13/UllFnaWA9kpE+Mvw8c0rYBcsFe69/Ty5rxk3zZxoSoiefb4kes8K6/mXABl20=
matrix:
  include:
  - rvm: 2.5.1
after_success:
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent)" 
- ssh-add
- openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out
  config/deploy_id_rsa
- bundle exec cap production deploy

