
default: &default
  database: crm_dev
  adapter: postgresql
  username: root
  password: root
  pool: 50
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: travis_ci_test
  username: postgres
  password: postgres
  pool: 50
  timeout: 5000
  
development:
  <<: *default
