default: &default
  database: crm_dev
  adapter: postgresql
  username: postgres
  password: postgres
  pool: 50
  timeout: 5000
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: travis_ci_test
  username: postgres
  password: postgres
  pool: 50
  timeout: 5000
  host: localhost
  port: 5432
  
development:
  <<: *default
